### ISSUE TITLE
ConcatList iterator is horrifyingly slow

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shape-functional-java#2]
Eg, creating a list of 30 items by appending them one at a time creates a binary tree of depth 30, and iterating through it thus requires creating 30 nested iterators, which is apparently slow.

**Comment by ikarienator** [comment]
If we turn it into a stack of zippers, it is not going to be faster, but it will not exhaust the call stack.
Any idea on how this can be faster (than creating d( = depth) objects)?

**Comment by bakkot** [comment]
Turn into an ImmutableList and expose an iterator on that. Alternatively, don't even expose an iterator; you can do `for (A a : concatList.toList());` instead.

**Comment by ikarienator** [comment]
Well, an `ImmutableList` is `n` objects, which is actually more than `d` objects. Let alone the huge overhead of `ImmutableList`. Also, to convert a tree to a list needs a stack of size `d`, which is equivalent to what you pay in the current iterator implementation.

All time complexity is linear. The cost is mostly GC related. Then the structure of linked list, in fact, is really bad in terms of GC (for example, the mark-and-sweep is completely serialized, preventing GC from running in parallel).

Also don't forget that iterating an iterator can early terminate but converting it to a copy of the list cannot.

A `for` loop in Java uses an iterator behind the scene. You cannot use for loop without exposing the iterator.

**Comment by ikarienator** [comment]
[This PR](https://github.com/shapesecurity/shape-functional-java/pull/24) sped up the iterator for about 25 times. Is it enough?
