### ISSUE TITLE
HashTable::from

### ISSUE THREAD

**Issue by Protryon** [shapesecurity/shape-functional-java#71]
It would be nice to have a few implementations of `HashTable::from`, example prototypes:
* `HashTable::<A, B>from(ImmutableList<Pair<A, B>>)`
* `HashTable::<A, B>from(java.util.Map<A, B>)`

The same can be said for `ImmutableSet` and the corresponding types.

**Comment by michaelficarra** [comment]
Fixed by #77 and #88.
